version: '3'
services:
    php-fpm:
        restart: always
        container_name: sas_php
        build:
            context: .docker/php

    nginx:
        restart: always
        container_name: sas_nginx
        build:
            context: .docker/nginx
        ports:
            - "8891:80"
        depends_on:
            - php-fpm