apiVersion: apps/v1
kind: Deployment
metadata:
    name: simple-api-service
    labels:
        app: simple-api-service
        environment: staging
spec:
    replicas: 1
    selector:
        matchLabels:
            app: simple-api-service
    template:
        metadata:
            labels:
                app: simple-api-service
                environment: staging
        spec:
            containers:
                -   name: php-fpm
                    image: nezhkind/simple-api-service_php-fpm:latest
                    ports:
                        -   containerPort: 80
                        -   containerPort: 9000
                -   name: nginx
                    image: nezhkind/simple-api-service_nginx:latest
                    ports:
                        -   containerPort: 80
