apiVersion: apps/v1
kind: Deployment
metadata:
    name: simple-api-service
    labels:
        app: simple-api-service
        environment: production
spec:
    replicas: 2
    selector:
        matchLabels:
            app: simple-api-service
    template:
        metadata:
            labels:
                app: simple-api-service
        spec:
            containers:
                -   name: php-fpm
                    image: nezhkind/simple-api-service_php-fpm:latest
                    ports:
                        -   containerPort: 80
                        -   containerPort: 9000
                -   name: nginx
                    image: nezhkind/simple-api-service_nginx:latest
                    ports:
                        -   containerPort: 80