apiVersion: v1
kind: Service
metadata:
    name: simple-api-service
spec:
    selector:
        app: simple-api-service
        environment: production
    ports:
       -   protocol: TCP
           port: 80
           targetPort: 80
       -   protocol: TCP
           port: 9000
           targetPort: 9000
    type: NodePort
