name: Deploy to Remote Server

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Deploy application
              env:
                  REMOTE_USER: "dnezhkin"                                        # Имя пользователя на сервере
                  REMOTE_HOST: "176.123.160.245"                                 # Адрес сервера
                  REMOTE_PATH: "/home/dnezhkin/apps/simple-api-service"          # Путь к приложению на сервере
              run: |
                  ssh ${REMOTE_USER}@${REMOTE_HOST} "cd ${REMOTE_PATH} && make rerun"