name: Build and Test

on:
    push:
        branches-ignore:
            - main  # Исключаем векту main
    pull_request:

jobs:
    build-and-test:
        strategy:
            matrix:
                os: [ ubuntu-latest, macos-latest ]  # Добавляем ОС
        runs-on: ${{ matrix.os }}  # Используем текущую ОС из матрицы

        steps:
            # Клонируем репозиторий
            -   name: Checkout code
                uses: actions/checkout@v3

            # Устанавливаем docker-compose (только для Linux)
            -   name: Set up Docker Compose
                if: runner.os == 'Linux'
                run: |
                    sudo apt-get update
                    sudo apt-get install -y docker-compose

            # Устанавливаем docker и docker-compose на macOS
            # Ожидаем запуска docker-compose
            -   name: Install Docker on macOS
                if: runner.os == 'macOS'
                run: |
                    brew install --cask docker
                    open /Applications/Docker.app
                    brew install docker-compose
                    sleep 10  # Ожидаем запуска Docker Engine

            # Показать список файлов
            -   name: List repository files
                if: runner.os == 'Linux'
                run: ls -R

            # Сборка контейнеров через docker-compose
            -   name: Build Docker containers
                run: sudo docker-compose -f docker-compose.yaml build

            # Запускаем сервисы через docker-compose
            -   name: Start Docker Compose services
                run: sudo docker-compose -f docker-compose.yaml up -d

            # Установка зависимостей через Composer
            -   name: Install dependencies
                run: sudo docker exec sas_php composer install

            # Запуск тестов
            -   name: Run PHPUnit tests
                run: sudo docker exec sas_php php bin/phpunit

            # Остановка и удаление контейнеров
            -   name: Stop and clean up Docker Compose
                if: always()
                run: sudo docker-compose -f docker-compose.yaml down
