name: Build and Test

on:
    push:
        branches-ignore:
            - main  # Исключаем векту main
    pull_request:

jobs:
    build-and-test:
        strategy:
            matrix:
                os: [ ubuntu-latest, macos-latest, windows-latest ]  # Добавляем ОС
        runs-on: ${{ matrix.os }}  # Используем текущую ОС из матрицы

        steps:
            # Клонируем репозиторий
            -   name: Checkout code
                uses: actions/checkout@v3

            # Устанавливаем docker-compose (только для Linux)
            -   name: Set up Docker Compose
                if: runner.os == 'Linux'
                run: |
                    sudo apt-get update
                    sudo apt-get install -y docker-compose

            # Устанавливаем docker-compose (только для Windows)
            -   name: Set up Docker Compose
                if: runner.os == 'Windows'
                run: |
                    choco install php --version=8.1.0 -y
                    choco install composer -y   
                    Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
                    refreshenv

            # Проверка версий PHP и Composer
            -   name: Check PHP and Composer versions (Windows only)
                if: runner.os == 'Windows'
                run: |
                    php --version
                    composer --version

            # Устанавливаем php и composer на macOS
            # Загружаем пакеты через composer
            -   name: Install php, composer, make (macOS only)
                if: runner.os == 'macOS'
                run: |
                    brew install php
                    brew install composer
                    brew install make

            # Показать список файлов (для отладки)
            -   name: List repository files
                if: runner.os != 'Windows'
                run: |
                    ls -R
                    pwd
                    ls -la

            # Сборка контейнеров через docker-compose (Linux)
            -   name: Build Docker containers (Linux only)
                if: runner.os == 'Linux'
                run: docker-compose -f docker-compose.yaml build

            # Запускаем сервисы через docker-compose (Linux)
            -   name: Start Docker Compose services (Linux only)
                if: runner.os == 'Linux'
                run: docker-compose -f docker-compose.yaml up -d

            # Установка зависимостей через Composer (Linux)
            -   name: Install dependencies (Linux only)
                if: runner.os == 'Linux'
                run: docker exec sas_php composer install

            # Установка зависимостей через Composer (Linux)
            -   name: Install dependencies (macOS only)
                if: runner.os != 'Linux'
                run: cd ./app && composer update

            # Запуск тестов (Linux)
            -   name: Run PHPUnit tests (Linux only)
                if: runner.os == 'Linux'
                run: docker exec sas_php php bin/phpunit

            # Запуск тестов (Mac)
            -   name: Run PHPUnit tests (macOS only)
                if: runner.os != 'Linux'
                run: cd ./app && php ./bin/phpunit

            # Остановка и удаление контейнеров
            -   name: Stop and clean up Docker Compose (Linux only)
                if: always() && runner.os == 'Linux'
                run: docker-compose -f docker-compose.yaml down
