name: Build and Test

on:
    push:
        branches-ignore:
            - main  # Исключаем векту main
    pull_request:

jobs:
    build-and-test:
        strategy:
            matrix:
                os: [ ubuntu-latest, macos-latest, windows-latest]  # Добавляем ОС
        runs-on: ${{ matrix.os }}  # Используем текущую ОС из матрицы

        services:
            # Настраиваем Docker Compose
            docker:
                image: docker/compose:latest

        steps:
            # Клонируем репозиторий
            -   name: Checkout code
                uses: actions/checkout@v3

            # Устанавливаем Docker Compose (только для Linux)
            -   name: Set up Docker Compose
                if: runner.os == 'Linux'
                run: |
                    sudo apt-get update
                    sudo apt-get install -y docker-compose

            # Устанавливаем Docker на macOS
            # Ожидаем запуска Docker Engine
            -   name: Install Docker on macOS
                if: runner.os == 'macOS'
                run: |
                    brew install docker-compose
                    sleep 10 

            # Показать список файлов
            -   name: List repository files
                if: runner.os == 'Linux'
                run: ls -R

            # Сборка контейнеров через Docker Compose
            -   name: Build Docker containers
                run: docker-compose -f docker-compose.yaml build

            # Запускаем сервисы через Docker Compose
            -   name: Start Docker Compose services
                run: docker-compose -f docker-compose.yaml up -d

            # Установка зависимостей через Composer
            -   name: Install dependencies
                run: docker exec sas_php composer install

            # Запуск тестов
            -   name: Run PHPUnit tests
                run: docker exec sas_php php bin/phpunit

            # Остановка и удаление контейнеров
            -   name: Stop and clean up Docker Compose
                if: always()
                run: docker-compose -f docker-compose.yaml down
